include "Types.fbs";
include "ErrorCodes.fbs";

namespace SyncnetPlatform.Protocols.Generated;

table ReqCreateRoom{
    name: string;
    private: bool = false;
    password: string;
    max_count: int;
}

table ResCreateRoom{
    result: PacketErrorCodes;
    room_id: GuidType;
    room_metadata: [ubyte];
}

table ReqJoinRoom{
    room_id: GuidType;
    password: string;
}

table ResJoinRoom{
    result: PacketErrorCodes;
    app_error_code: int;
    room_metadata: [ubyte];
}
table OnPlayerJoinRoom{
    room_id: GuidType;
    joiner_id: GuidType;
    joiner_name: string;
    joiner_metadata: [ubyte];
}

table ReqPlayerListInRoom{
    room_id: GuidType;
}

table ResPlayerListInRoom{
    room_id: GuidType;
    members: [PlayerInfoInRoom];
}

table OnPlayRoomUpdate  {
    room_id: GuidType;
    metadata: [ubyte];
}

table OnPlayRoomUpdatePlayer {
    ids: GuidType;
    metadata: [ubyte];
}

table ReqLeaveRoom{
    room_id: GuidType;
}

table ResLeaveRoom{
    result: PacketErrorCodes;
}

// Notify other player leaves.
table OnPlayerLeaveRoom {
    room_id: GuidType;
    player_id: GuidType;
    name: string;
}

table ReqBroadcastRoom{
    room_id: GuidType;
    from: GuidType;
    message: string;
}

table ResBroadcastRoom{
    result: PacketErrorCodes;
}

table BroadcastRoom{
    from: GuidType;
    message: string;
}
