include "Types.fbs";
include "ErrorCodes.fbs";

namespace SyncnetPlatform.Protocols.Generated;



table ReqUserInfo{
}

table ResUserInfo{
    player_id: GuidType;
    player_name: string;
    player_custom: [ubyte];
}

table ReqUpdatePlayerName{
    player_name: string;
}
table ResUpdatePlayerName{
    result: PacketErrorCodes;
}

table ReqUserActionForUpdatePlayerCustomData {
    action_type: string;
    action_parameter: [ubyte];
}

table ResUserActionForUpdatePlayerCustomData {
    result: PacketErrorCodes;
    message: string;
    player_custom: [ubyte];
}

table ReqDirectDeliveryData {
    to_player_id: GuidType;
    data: string;
    data_type: DirectDeliveryDataType;
}

table ResDirectDeliveryData {
    result: PacketErrorCodes;
    message: string;
}

table OnDirectDeliveryData {
    from_player_id: GuidType;
    data: string;
    data_type: DirectDeliveryDataType;
} 

table DeliverCustomPacket {
    destination: DeliverDestination;
    custom_packet: [ubyte] ;
}
