include "Types.fbs";
include "ErrorCodes.fbs";

namespace SyncnetPlatform.Protocols.Generated;



table ReqUserInfo{
}

table ResUserInfo{
    id: GuidType;
    name: string;
    extend_data: [ubyte];
}

table ReqUpdatePlayerName{
    player_name: string;
}
table ResUpdatePlayerName{
    result: PacketErrorCodes;
}

// 사용자 액션에 의한 메타 데이타 업데이트 처리 요청 패킷 
table ReqUserActionForUpdatePlayerCustomData {
    action_type: string;
    action_parameter: [ubyte];
}

table ResUserActionForUpdatePlayerCustomData {
    result: PacketErrorCodes;
    app_error_code: int; // 게임에서 정의한 에러 코드 전송 
    message: string;
    player_custom: [ubyte];
}

table ReqDirectDeliveryData {
    to_player_id: GuidType;
    data: string;
    data_type: DirectDeliveryDataType;
}

table ResDirectDeliveryData {
    result: PacketErrorCodes;
    message: string;
}

table OnDirectDeliveryData {
    from_player_id: GuidType;
    data: string;
    data_type: DirectDeliveryDataType;
} 

table DeliverCustomPacket {
    destination: DeliverDestination;
    custom_packet: [ubyte] ;
}
