include "Types.fbs";
include "ErrorCodes.fbs";

namespace SyncnetPlatform.Protocols.Generated;

table ReqCreateRoom{
    name: string;
    private: bool = false;
    password: string;
    max_count: int;
}

table ResCreateRoom{
    result: PacketErrorCodes;
    room_id: GuidType;
    room_state: [ubyte];
}

table ReqJoinRoom{
    room_id: GuidType;
    password: string;
}

table ResJoinRoom{
    result: PacketErrorCodes;
    app_error_code: int;
    room_state: [ubyte];
}
table OnPlayerJoinRoom{
    room_id: GuidType;
    joiner_id: GuidType;
    joiner_name: string;
    joiner_metadata: [ubyte];
}

table ReqPlayerListInRoom{
    room_id: GuidType;
}

table ResPlayerListInRoom{
    room_id: GuidType;
    members: [PlayerInfoInRoom];
}

// 게임모드 진행에 변경 사항에 생겼을 경우 전체에 브로드 캐스팅
table OnPlayRoomUpdate  {
    room_id: GuidType;
    metadata: [ubyte];
}

// 특정 사용자의 정보가 업데이트 되었을 경우 전체에 브로드 캐스팅 
table OnPlayRoomUpdatePlayer {
    id: GuidType;
    metadata: [ubyte];
}

// 사용자의 특정 액션이 발생했고 게임 모드 진행에 변경을 요구할 경우 전송 
table ReqPlayerActionToPlayRoom {
    room_id: GuidType;
    action_type: string;
    action_parameter: [ubyte];
}

table ResPlayerActionToPlayRoom {
    result: PacketErrorCodes;
    app_error_code: int;
}

table ReqLeaveRoom{
    room_id: GuidType;
}

table ResLeaveRoom{
    result: PacketErrorCodes;
}

// Notify other player leaves.
table OnPlayerLeaveRoom {
    room_id: GuidType;
    player_id: GuidType;
    name: string;
}

table ReqBroadcastRoom{
    room_id: GuidType;
    from: GuidType;
    message: string;
}

table ResBroadcastRoom{
    result: PacketErrorCodes;
}

table BroadcastRoom{
    from: GuidType;
    message: string;
}
