

include "Player.fbs";
include "Playroom.fbs";

namespace SyncnetPlatform.Protocols.Generated;


union SystemPacket {
    Ping,
    Pong,
    ReqUserInfo,
    ResUserInfo,
    ReqUserActionForUpdatePlayerExtendData,
    ResUserActionForUpdatePlayerExtendData,
    ReqDirectDeliveryData,
    ResDirectDeliveryData,
    OnDirectDeliveryData,
    ReqCreateRoom,
    ResCreateRoom,
    ReqJoinRoom,
    ResJoinRoom,
    OnPlayerJoinRoom,
    ReqPlayerListInRoom,
    ResPlayerListInRoom,
    OnPlayRoomUpdate,
    OnPlayRoomUpdatePlayer,
    ReqPlayerActionToPlayRoom,
    ResPlayerActionToPlayRoom,
    ReqLeaveRoom,
    ResLeaveRoom,
    OnPlayerLeaveRoom,
    ReqBroadcastRoom,
    ResBroadcastRoom,
    BroadcastRoom,
    ReqUpdatePlayerName,
    ResUpdatePlayerName,
    DeliverCustomPacket
}

table PacketWrapper {
    system_packet: SystemPacket;
}


table Ping {
    seq: int;
}
table Pong {
    seq: int;
}


root_type PacketWrapper;
