// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncnetPlatform.Dto
{

public enum CustomPacket : byte
{
  NONE = 0,
  MyCustomPacket = 1,
};



static public class CustomPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((CustomPacket)typeId)
    {
      case CustomPacket.MyCustomPacket:
        result = SyncnetPlatform.Dto.MyCustomPacketVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
