// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncnetPlatform.Dto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Dummy : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Dummy GetRootAsDummy(ByteBuffer _bb) { return GetRootAsDummy(_bb, new Dummy()); }
  public static Dummy GetRootAsDummy(ByteBuffer _bb, Dummy obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Dummy __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SyncnetPlatform.Dto.Dummy> CreateDummy(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartTable(1);
    Dummy.AddId(builder, id);
    return Dummy.EndDummy(builder);
  }

  public static void StartDummy(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<SyncnetPlatform.Dto.Dummy> EndDummy(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SyncnetPlatform.Dto.Dummy>(o);
  }
}


static public class DummyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
