// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncnetPlatform.Dto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct MyCustomPacket : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static MyCustomPacket GetRootAsMyCustomPacket(ByteBuffer _bb) { return GetRootAsMyCustomPacket(_bb, new MyCustomPacket()); }
  public static MyCustomPacket GetRootAsMyCustomPacket(ByteBuffer _bb, MyCustomPacket obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MyCustomPacket __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Id { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIdBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetIdBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetIdArray() { return __p.__vector_as_array<byte>(4); }
  public float X { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<SyncnetPlatform.Dto.MyCustomPacket> CreateMyCustomPacket(FlatBufferBuilder builder,
      StringOffset idOffset = default(StringOffset),
      float x = 0.0f,
      float y = 0.0f) {
    builder.StartTable(3);
    MyCustomPacket.AddY(builder, y);
    MyCustomPacket.AddX(builder, x);
    MyCustomPacket.AddId(builder, idOffset);
    return MyCustomPacket.EndMyCustomPacket(builder);
  }

  public static void StartMyCustomPacket(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddId(FlatBufferBuilder builder, StringOffset idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(1, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(2, y, 0.0f); }
  public static Offset<SyncnetPlatform.Dto.MyCustomPacket> EndMyCustomPacket(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SyncnetPlatform.Dto.MyCustomPacket>(o);
  }
}


static public class MyCustomPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Id*/, false)
      && verifier.VerifyField(tablePos, 6 /*X*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Y*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
