// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncnetPlatform.Dto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct PacketWrapper : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static PacketWrapper GetRootAsPacketWrapper(ByteBuffer _bb) { return GetRootAsPacketWrapper(_bb, new PacketWrapper()); }
  public static PacketWrapper GetRootAsPacketWrapper(ByteBuffer _bb, PacketWrapper obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyPacketWrapper(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, PacketWrapperVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public PacketWrapper __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SyncnetPlatform.Dto.SystemPacket SystemPacketType { get { int o = __p.__offset(4); return o != 0 ? (SyncnetPlatform.Dto.SystemPacket)__p.bb.Get(o + __p.bb_pos) : SyncnetPlatform.Dto.SystemPacket.NONE; } }
  public TTable? SystemPacket<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public SyncnetPlatform.Dto.LoginRequest SystemPacketAsLoginRequest() { return SystemPacket<SyncnetPlatform.Dto.LoginRequest>().Value; }
  public SyncnetPlatform.Dto.MoveRequest SystemPacketAsMoveRequest() { return SystemPacket<SyncnetPlatform.Dto.MoveRequest>().Value; }
  public SyncnetPlatform.Dto.CustomPacket CustomPacketType { get { int o = __p.__offset(8); return o != 0 ? (SyncnetPlatform.Dto.CustomPacket)__p.bb.Get(o + __p.bb_pos) : SyncnetPlatform.Dto.CustomPacket.NONE; } }
  public TTable? CustomPacket<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(10); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public SyncnetPlatform.Dto.MyCustomPacket CustomPacketAsMyCustomPacket() { return CustomPacket<SyncnetPlatform.Dto.MyCustomPacket>().Value; }

  public static Offset<SyncnetPlatform.Dto.PacketWrapper> CreatePacketWrapper(FlatBufferBuilder builder,
      SyncnetPlatform.Dto.SystemPacket system_packet_type = SyncnetPlatform.Dto.SystemPacket.NONE,
      int system_packetOffset = 0,
      SyncnetPlatform.Dto.CustomPacket custom_packet_type = SyncnetPlatform.Dto.CustomPacket.NONE,
      int custom_packetOffset = 0) {
    builder.StartTable(4);
    PacketWrapper.AddCustomPacket(builder, custom_packetOffset);
    PacketWrapper.AddSystemPacket(builder, system_packetOffset);
    PacketWrapper.AddCustomPacketType(builder, custom_packet_type);
    PacketWrapper.AddSystemPacketType(builder, system_packet_type);
    return PacketWrapper.EndPacketWrapper(builder);
  }

  public static void StartPacketWrapper(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddSystemPacketType(FlatBufferBuilder builder, SyncnetPlatform.Dto.SystemPacket systemPacketType) { builder.AddByte(0, (byte)systemPacketType, 0); }
  public static void AddSystemPacket(FlatBufferBuilder builder, int systemPacketOffset) { builder.AddOffset(1, systemPacketOffset, 0); }
  public static void AddCustomPacketType(FlatBufferBuilder builder, SyncnetPlatform.Dto.CustomPacket customPacketType) { builder.AddByte(2, (byte)customPacketType, 0); }
  public static void AddCustomPacket(FlatBufferBuilder builder, int customPacketOffset) { builder.AddOffset(3, customPacketOffset, 0); }
  public static Offset<SyncnetPlatform.Dto.PacketWrapper> EndPacketWrapper(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SyncnetPlatform.Dto.PacketWrapper>(o);
  }
  public static void FinishPacketWrapperBuffer(FlatBufferBuilder builder, Offset<SyncnetPlatform.Dto.PacketWrapper> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedPacketWrapperBuffer(FlatBufferBuilder builder, Offset<SyncnetPlatform.Dto.PacketWrapper> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class PacketWrapperVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*SystemPacketType*/, 1 /*SyncnetPlatform.Dto.SystemPacket*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*SystemPacket*/, SyncnetPlatform.Dto.SystemPacketVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*CustomPacketType*/, 1 /*SyncnetPlatform.Dto.CustomPacket*/, 1, false)
      && verifier.VerifyUnion(tablePos, 8, 10 /*CustomPacket*/, SyncnetPlatform.Dto.CustomPacketVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
