// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SyncnetPlatform.Dto
{

public enum SystemPacket : byte
{
  NONE = 0,
  LoginRequest = 1,
  MoveRequest = 2,
};



static public class SystemPacketVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((SystemPacket)typeId)
    {
      case SystemPacket.LoginRequest:
        result = SyncnetPlatform.Dto.LoginRequestVerify.Verify(verifier, tablePos);
        break;
      case SystemPacket.MoveRequest:
        result = SyncnetPlatform.Dto.MoveRequestVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
