<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
  </ItemGroup>
  <Target Name="FlatcGenerate" BeforeTargets="BeforeCompile">
    <Message Text="Running flatc code generator" Importance="high" />
    <RemoveDir Directories="./generated" />
    <Exec Command="flatc -n -o ./generated ./PacketDefinitions/Player.fbs" />
    <Exec Command="flatc -n -o ./generated ./PacketDefinitions/TGame.fbs" />
    <ItemGroup>
        <NewGeneratedFiles Include="generated/**/*.cs" />
        <NewGeneratedFiles Remove="@(Compile)" />
        <Compile Include="@(NewGeneratedFiles)" />
    </ItemGroup>
</Target>
</Project>
