<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SyncnetPlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="generated\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.17.0" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Dashboard" Version="10.0.1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="10.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Authentication\Guest\" />
    <Folder Include="Migrations\" />
    <Folder Include="Exceptions\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AppServiceDefault\AppServiceDefault.csproj" />
  </ItemGroup>
  
	<Target Name="FlatcGenerate" BeforeTargets="BeforeCompile">
		<Message Text="Running flatc code generator" Importance="high" />
		<RemoveDir Directories="./generated" />
		<Exec Command="flatc -n -o ./generated ./fbs/Types.fbs" />
		<Exec Command="flatc -n -o ./generated ./fbs/ErrorCodes.fbs" />
		<Exec Command="flatc -n -o ./generated ./fbs/System.fbs" />
		<Exec Command="flatc -n -o ./generated ./fbs/Player.fbs" />
		<Exec Command="flatc -n -o ./generated ./fbs/Custom.fbs" />
		<Exec Command="flatc -n -o ./generated ./fbs/Playroom.fbs" />
		<ItemGroup>
			<Compile Include="./generated/**/*.cs" />
		</ItemGroup>
	</Target>

</Project>
