<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SyncnetPlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="9.2.1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="9.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABMGS.ServerV2.Shared\ABMGS.ServerV2.Shared.csproj" />
  </ItemGroup>

<ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>


	<ItemGroup>
    <Folder Include="SyncnetPlatform\Protocols\" />
  </ItemGroup>

</Project>
