<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SyncnetPlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
    
    <PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="9.2.1" />
    <PackageReference Include="Microsoft.Orleans.Server" Version="9.2.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="flatc -n -o ./generated System.fbs" />
		<Exec Command="flatc -n -o ./generated Custom.fbs" />
	</Target>

</Project>
