include "Types.fbs";
include "ErrorCodes.fbs";

namespace SyncnetPlatform.Protocols.Generated;



table ReqUserInfo{
}

table ResUserInfo{
    player_id: GuidType;
    player_name: string;
}

table ReqUpdatePlayerName{
    player_name: string;
}
table ResUpdatePlayerName{
    result: int;
    message: string;
}

table ReqDirectDeliveryData {
    to_player_id: GuidType;
    data: string;
    data_type: DirectDeliveryDataType;
}

table ResDirectDeliveryData {
    result: PacketErrorCodes;
    message: string;
}

table OnDirectDeliveryData {
    from_player_id: GuidType;
    data: string;
    data_type: DirectDeliveryDataType;
} 
