sequenceDiagram
participant Player1
participant PlayRoom1
participant Player2

Note over Player1,PlayRoom1: Case: Creating new play room
Player1->>PlayRoom1: ReqCreatePlayRoom
PlayRoom1->>Player1: ResCreatePlayRoom

Note over Player1,Player2: Case: Player1 invites Player2
Player1->>Player2: ReqInvitePlayRoom
Player2->>Player1: ResInvitePlayRoom

Note over Player1,Player2: Case: Player2 Joins to a play room and notifying to inner players
Player2->>PlayRoom1: ReqJoinPlayRoom
PlayRoom1->>Player2: ResJoinPlayRoom
PlayRoom1->>Player1: ResJoinPlayRoom

Note over Player2,PlayRoom1: Case: Getting player's info already in
Player2->>PlayRoom1: ReqPlayersInfo
PlayRoom1->>Player2: ResPlayersInfo

Note over Player1,Player2: Case: Leaving player2
Player2->>PlayRoom1: ReqLeavePlayRoom
PlayRoom1->>Player2: ResLeavePlayRoom
PlayRoom1->>Player1: ResLeavePlayRoom





