include "Types.fbs";
include "ErrorCodes.fbs";

namespace SyncnetPlatform.Protocols.Generated;

table ReqCreateRoom{
    name: string;
    private: bool = false;
    password: string;
    max_count: int;
}

table ResCreateRoom{
    result: PacketErrorCodes;
    room_id: GuidType;
}

table ReqJoinRoom{
    room_id: GuidType;
    password: string;
}

table ResJoinRoom{
    result: PacketErrorCodes;
}
table OnPlayerJoinRoom {
    room_id: GuidType;
    player_id: GuidType;
    name: string;
}

table ReqLeaveRoom{
    room_id: GuidType;
}

table ResLeaveRoom{
    result: PacketErrorCodes;
}

// Notify other player leaves.
table OnPlayerLeaveRoom {
    room_id: GuidType;
    player_id: GuidType;
    name: string;
}

table ReqBroadcastRoom{
    room_id: GuidType;
    from: GuidType;
    message: string;
}

table ResBroadcastRoom{
    result: PacketErrorCodes;
}

table BroadcastRoom{
    from: GuidType;
    message: string;
}

table ReqDestroyRoom {
    room_id: GuidType;
    reason: string;
}

