

include "Custom.fbs";
include "Player.fbs";
include "Playroom.fbs";

namespace SyncnetPlatform.Protocols.Generated;


union SystemPacket {
    Ping,
    Pong,
    ReqCreateNewUser,
    ResCreateNewUser,
    ReqUserInfo,
    ResUserInfo,
    ReqCreateRoom,
    ResCreateRoom,
    ReqJoinRoom,
    ResJoinRoom,
    ReqLeaveRoom,
    ResLeaveRoom,
    ReqBroadcastRoom,
    ResBroadcastRoom,
    BroadcastRoom,
}

table PacketWrapper {
    system_packet: SystemPacket;
    custom_packet: CustomPacket;
}


table Ping {
    seq: int;
}
table Pong {
    seq: int;
}


root_type PacketWrapper;
