<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.Development.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Development.json" />
  </ItemGroup>

	<ItemGroup>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<DependentUpon>appsettings.json</DependentUpon>
		</Content>
	</ItemGroup>


<ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Orleans.Clustering.Redis" Version="9.2.1" />
	<PackageReference Include="Microsoft.Orleans.Server" Version="9.2.1" />
</ItemGroup>
<ItemGroup>
  <ProjectReference Include="..\ABMGS.Serverv2.Package\ABMGS.Serverv2.Package.csproj" />
</ItemGroup>

<ItemGroup>
  <None Update="Properties\launchSettings.json">
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <CopyToPublishDirectory>Never</CopyToPublishDirectory>
  </None>
</ItemGroup>

</Project>
