@ABMGS.ServerV2_HostAddress = http://localhost:5100

GET {{ABMGS.ServerV2_HostAddress}}/ws/alive
#Accept: application/json

###

GET {{ABMGS.ServerV2_HostAddress}}/api/healthy

###
GET {{ABMGS.ServerV2_HostAddress}}/api/auth/token/test/20250815
