<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SyncnetPlatform</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.FlatBuffers" Version="25.2.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABMGS.Serverv2.Package\ABMGS.Serverv2.Package.csproj" />
    <ProjectReference Include="..\AppServiceDefault\AppServiceDefault.csproj" />
  </ItemGroup>

</Project>
