include "Custom.fbs";

namespace SyncnetPlatform.Protocols.Generated;


struct GuidType {
    bytes: [ubyte:16];
}

union SystemPacket {
    Ping,
    Pong,
    ReqUserInfo,
    ResUserInfo
}

table PacketWrapper {
    system_packet: SystemPacket;
    custom_packet: CustomPacket;
}


table Ping {
    seq: int;
}
table Pong {
    seq: int;
}

table ReqUserInfo {
    
}

table ResUserInfo {
    player_id: GuidType;
    player_name: string;
    level :int;
    exp: ulong;
}

root_type PacketWrapper;
