@ABMGS.Server_HostAddress = http://localhost:5131

GET {{ABMGS.Server_HostAddress}}/
Accept: application/json

###

GET {{ABMGS.Server_HostAddress}}/shorten?url=https://www.naver.com
Accept: application/json
###

GET {{ABMGS.Server_HostAddress}}/go/7DFD5544