// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ABMGS.ServerV2.Silo.Migrations
{
    [DbContext(typeof(SyncnetDbContextExtend))]
    [Migration("20251129061522_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerDataModelExtend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Exp")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerDataModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerDataModelId");

                    b.ToTable("players_extend");
                });

            modelBuilder.Entity("SyncnetPlatform.Databases.PlayerDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("PlayerDataModelExtend", b =>
                {
                    b.HasOne("SyncnetPlatform.Databases.PlayerDataModel", "PlayerDataModel")
                        .WithMany()
                        .HasForeignKey("PlayerDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerDataModel");
                });
#pragma warning restore 612, 618
        }
    }
}
